# See:
#   https://github.com/elgohr/Publish-Docker-Github-Action
#   https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/
#   https://docs.docker.com/docker-hub/access-tokens/

# I would use a Docker Hub automated build instead of this, but I need BuildKit
# (https://github.com/moby/moby/issues/35699)
# and the Docker version on Docker Hub is super outdated.  Oh well, this is
# faster anyway.

name: Check, build
on:
  push:
  release:
    types: [published]

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
    - name: Install and run pre-commit
      run: |
        pip install pre-commit
        pre-commit run -a -v
  Build:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install latest Docker
      run: |
        curl -fsSL https://get.docker.com | sudo sh
    - name: Log in to registry
      env:
        USERNAME: mjenz
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin
    - name: Fetch dependencies
      run: |
        docker pull mjenz/zerotier-dns:builder || true
        DOCKER_BUILDKIT=1 docker build \
          --target builder \
          --cache-from mjenz/zerotier-dns:builder \
          -t mjenz/zerotier-dns:builder \
          .
        docker push mjenz/zerotier-dns:builder
    - name: Construct Docker image name
      if: github.event_name == 'push'
      run: |
        echo "IMAGE=mjenz/zerotier-dns:latest" >> $GITHUB_ENV
    - name: Construct Docker image name
      if: github.event_name == 'release'
      run: |
        echo "IMAGE=mjenz/zerotier-dns:${{ github.event.release.tag_name }}" >> $GITHUB_ENV
    - name: Build image
      run: |
        DOCKER_BUILDKIT=1 docker build \
          --cache-from mjenz/zerotier-dns:builder \
          -t $IMAGE \
          .
    - name: Push image
      if: (github.ref == 'refs/heads/master' || github.event_name == 'release')
      run: |
        docker push $IMAGE
    - name: Update Docker Hub description
      if: github.ref == 'refs/heads/master'
      uses: peter-evans/dockerhub-description@v2.4.1
      with:
        username: mjenz
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mjenz/zerotier-dns
